# примеры API-запросов

@baseUrl = https://localhost:8001/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# получение заголовков объявлений
HEAD {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 72034f51d0a14be5641efd76bd3a18eedc39a226

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# Удаление объявления 
DELETE  {{baseUrl}}/advertisements/2/
