# примеры API-запросов

@baseUrl = http://localhost:8001/api

# получение датчиков
GET {{baseUrl}}/sensors_list/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP36 ",
  "description": "Датчик в ванную комнату"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 23.5
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json


###

# получение данных по температурам
GET {{baseUrl}}/measurements/
Content-Type: application/json

